;[GROUPX]	where X is the scenario just played.
;			List of all regions conquered since last scenario.
;SAR	=	
;NEU 	=	
;ORD	=	
;			attack region, arrow#, x, y
;REG1	=	
;REG2	=
;REG3	=
;max text line is [------------------------------------------]
; at times, territories will be repeated that a house already has, this
; will give more time to read the text.

[GROUP1]
SAR	=	13, 7, 20, 14, 21, 22
NEU 	=	19, 27, 26, 25, 24, 23
ORD	=	6, 5, 4, 10, 3, 9
REG1	=	8, 3, 80, 80
REG2	=	15, 2, 101, 118
REG3	=	23, 3, 152, 136
ENGTXT13		=  The Harkonnen claimed strategic regions.
ENGTXT19		=  House Neutral moved in on the east.
ENGTXT6		=  The Sardaukar invaded from the north.
SARTXT13		=  Les Harkonnen ont revendiquÇ des rÇgions.
SARTXT19 	=  Les Neutral ont avancÇ Ö l'est.
SARTXT6  	=  Les Sardaukar ont envahi par le nord.
GERTXT13 	=  Harkonnen verlangen strategisch wichtige Gebiete fÅr sich.
GERTXT19 	=  Neutral sind in den Osten vorgerÅckt.
GERTXT6  	=  Sardaukar fallen von Norden her ein.

[GROUP2]
SAR	=	8, 15, 23, 15
NEU 	=	12, 18, 16, 17
ORD	=	1, 2, 11
REG1	=	1, 1, 32, 40
REG2	=	2, 2, 83, 58
REG3	=	3, 3, 122, 56
ENGTXT8		= Harkonnen captured more territory...
ENGTXT23		= ...and drove the Neutral out.
ENGTXT12		= Neutral headed for the Sardaukar.
ENGTXT1		= The Sardaukar expanded their borders.
SARTXT8  	= Les Harkonnen ont gagnÇ d'autres terres...
SARTXT23 	= ...et ont contraint les Neutral Ö fuir.
SARTXT12 	= Les Neutral se dirigent vers les Sardaukar.
SARTXT1  	= Les Sardaukar Çtendent leurs frontiäres.
GERTXT8 		= Harkonnen haben Neutral verfolgt.
;GERTXT8  	= Harkonnen haben noch mehr Land eingenommen...
;GERTXT23 	= ...und Neutral von dort vertrieben.
GERTXT12 	= Neutral stellen Sardaukar nach.
GERTXT1  	= Sardaukar haben ihre Grenzen ausgeweitet.

[GROUP3]
SAR 	=	1, 2, 3
NEU	=	11
ORD	=	16, 6
REG1	=	4, 3, 154, 32
REG2	=	9, 4, 139, 74
REG3	=	16, 3, 155, 97
ENGTXT1		=  The Sardaukar borders were weak...
ENGTXT16		=  ...except for one outpost.
SARTXT1  	=  La frontiäre Sardaukar Çtait faible...
SARTXT16 	=  ...Ö l'exception d'un avant-poste.
GERTXT1  	=  Grenzen der Sardaukar waren...
GERTXT11 	=  ...nicht gut gesichert...
GERTXT16 	=  von einem Vorposten abgesehen...

[GROUP4]
SAR 	=	4, 9, 16
ORD	=	11, 6
REG1	=	17, 3, 194, 74
REG2	=	25, 4, 198, 98
REG3	=	24, 3, 184, 125
ENGTXT4		=  The Sardaukar continued to retreat...
ENGTXT11		=  ...into the territory of the Neutral.
SARTXT4  	=  Les Sardaukar ont poursuivi leur retraite...
SARTXT11 	=  ...en territoire Neutral.
GERTXT4  	=  Sardaukar schoben sich immer weiter vor...
GERTXT11 	=  ...in das Gebiet der Neutral.

[GROUP5]
SAR 	=	17, 25, 24
ORD	=	18
REG1	=	10, 2, 208, 64
REG2	=	11, 4, 231, 76
REG3	=	18, 3, 247, 96
ENGTXT17		=  All forces were aimed at the Neutral.
SARTXT17 	=  Toutes les armÇes sont contre les Neutral.
GERTXT17 	=  Alle Truppen bekÑmpfen Neutral.

[GROUP6]
SAR 	=	10, 11, 18
REG1	=	19, 3, 283, 81
REG2	=	27, 5, 265, 100
REG3	=	26, 4, 223, 125
ENGTXT10		=  Harkonnen pushed the Neutral back further.
SARTXT10 	=  Les Harkonnen ont repoussÇ les Neutral.
;GERTXT10 	=  Harkonnen haben Neutral weiter zurÅckgedrÑngt.
GERTXT10 	=  Alle Truppen bekÑmpfen Neutral.

[GROUP7]
SAR 	=	26, 27, 19
REG1	=	5, 2, 237, 49
REG2	=	12, 2, 280, 64
ENGTXT26		=  The Neutral were nearly wiped out.
SARTXT26 	=  Les Neutral ont ÇtÇ presque exterminÇs.
GERTXT26 	=  Neutral sind fast vollstÑndig ausgerottet.

[GROUP8]
SAR 	=	5, 12
HAR	=	6
REG1	=	6, 3, 254, 27
REG2	=	6, 2, 288, 32
ENGTXT5	=  Only the Emperor's forces remain.
SARTXT5 	=  Il ne reste que l'armÇe de l'Empereur.
GERTXT5 	=  Nur die Truppen des Imperators Åberleben.

[PIECES]
1	=	0, 	0
2	=	55, 	0
3	=	97, 	0
4	=	145,	0
5	=	211,	0
6	=	247,	0
7	=	0,		9
8	=	71,	38
9	=	133,	31
10	=	173,	16
11	=	220,	22
12	=	264,	16
13	=	0,		41
14	=	21,	46
15	=	87,	70
16	=	148,	45
17	=	186,	45
18	=	243,	47
19	=	280,	47
20	=	0,		82
21	=	23,	91
22	=	59,	86
23	=	133,	92
24	=	172,	90
25	=	195,	70
26	=	216,	98
27	=	249,	77 

[INFO]
TOTAL REGIONS	= 	27
