;[GROUPX]	where X is the scenario just played.
;			List of all regions conquered since last scenario.
;MER	=	
;HAR 	=	
;FRE	=	
;			attack region, arrow#, x, y
;REG1	=	
;REG2	=
;REG3	=
;max text line is [------------------------------------------]
; at times, territories will be repeated that a house already has, this
; will give more time to read the text.

[GROUP1]
MER	=	13, 7, 20, 14, 21, 22
HAR 	=	19, 27, 26, 25, 24, 23
FRE	=	6, 5, 4, 10, 3, 9
REG1	=	8, 3, 80, 80
REG2	=	15, 2, 101, 118
REG3	=	23, 3, 152, 136
ENGTXT13		=  The Mercenary claimed strategic regions.
ENGTXT19		=  House Harkonnen moved in on the east.
ENGTXT6		=  The Fremen invaded from the north.
FRETXT13		=  Les Mercenary ont revendiquÇ des rÇgions.
FRETXT19 	=  Les Harkonnen ont avancÇ Ö l'est.
FRETXT6  	=  Les Fremen ont envahi par le nord.
GERTXT13 	=  Mercenary verlangen strategisch wichtige Gebiete fÅr sich.
GERTXT19 	=  Harkonnen sind in den Osten vorgerÅckt.
GERTXT6  	=  Fremen fallen von Norden her ein.

[GROUP2]
MER	=	8, 15, 23, 15
HAR 	=	12, 18, 16, 17
FRE	=	1, 2, 11
REG1	=	1, 1, 32, 40
REG2	=	2, 2, 83, 58
REG3	=	3, 3, 122, 56
ENGTXT8		= Mercenary captured more territory...
ENGTXT23		= ...and drove the Harkonnen out.
ENGTXT12		= Harkonnen headed for the Fremen.
ENGTXT1		= The Fremen expanded their borders.
FRETXT8  	= Les Mercenary ont gagnÇ d'autres terres...
FRETXT23 	= ...et ont contraint les Harkonnen Ö fuir.
FRETXT12 	= Les Harkonnen se dirigent vers les Fremen.
FRETXT1  	= Les Fremen Çtendent leurs frontiäres.
GERTXT8 		= Mercenary haben Harkonnen verfolgt.
;GERTXT8  	= Mercenary haben noch mehr Land eingenommen...
;GERTXT23 	= ...und Harkonnen von dort vertrieben.
GERTXT12 	= Harkonnen stellen Fremen nach.
GERTXT1  	= Fremen haben ihre Grenzen ausgeweitet.

[GROUP3]
MER 	=	1, 2, 3
HAR	=	11
FRE	=	16, 6
REG1	=	4, 3, 154, 32
REG2	=	9, 4, 139, 74
REG3	=	16, 3, 155, 97
ENGTXT1		=  The Fremen borders were weak...
ENGTXT16		=  ...except for one outpost.
FRETXT1  	=  La frontiäre Fremen Çtait faible...
FRETXT16 	=  ...Ö l'exception d'un avant-poste.
GERTXT1  	=  Grenzen der Fremen waren...
GERTXT11 	=  ...nicht gut gesichert...
GERTXT16 	=  von einem Vorposten abgesehen...

[GROUP4]
MER 	=	4, 9, 16
FRE	=	11, 6
REG1	=	17, 3, 194, 74
REG2	=	25, 4, 198, 98
REG3	=	24, 3, 184, 125
ENGTXT4		=  The Fremen continued to retreat...
ENGTXT11		=  ...into the territory of the Harkonnen.
FRETXT4  	=  Les Fremen ont poursuivi leur retraite...
FRETXT11 	=  ...en territoire Harkonnen.
GERTXT4  	=  Fremen schoben sich immer weiter vor...
GERTXT11 	=  ...in das Gebiet der Harkonnen.

[GROUP5]
MER 	=	17, 25, 24
FRE	=	18
REG1	=	10, 2, 208, 64
REG2	=	11, 4, 231, 76
REG3	=	18, 3, 247, 96
ENGTXT17		=  All forces were aimed at the Harkonnen.
FRETXT17 	=  Toutes les armÇes sont contre les Harkonnen.
GERTXT17 	=  Alle Truppen bekÑmpfen Harkonnen.

[GROUP6]
MER 	=	10, 11, 18
REG1	=	19, 3, 283, 81
REG2	=	27, 5, 265, 100
REG3	=	26, 4, 223, 125
ENGTXT10		=  Mercenary pushed the Harkonnen back further.
FRETXT10 	=  Les Mercenary ont repoussÇ les Harkonnen.
;GERTXT10 	=  Mercenary haben Harkonnen weiter zurÅckgedrÑngt.
GERTXT10 	=  Alle Truppen bekÑmpfen Harkonnen.

[GROUP7]
MER 	=	26, 27, 19
REG1	=	5, 2, 237, 49
REG2	=	12, 2, 280, 64
ENGTXT26		=  The Harkonnen were nearly wiped out.
FRETXT26 	=  Les Harkonnen ont ÇtÇ presque exterminÇs.
GERTXT26 	=  Harkonnen sind fast vollstÑndig ausgerottet.

[GROUP8]
MER 	=	5, 12
NEU	=	6
REG1	=	6, 3, 254, 27
REG2	=	6, 2, 288, 32
ENGTXT5	=  Only the Emperor's forces remain.
FRETXT5 	=  Il ne reste que l'armÇe de l'Empereur.
GERTXT5 	=  Nur die Truppen des Imperators Åberleben.

[PIECES]
1	=	0, 	0
2	=	55, 	0
3	=	97, 	0
4	=	145,	0
5	=	211,	0
6	=	247,	0
7	=	0,		9
8	=	71,	38
9	=	133,	31
10	=	173,	16
11	=	220,	22
12	=	264,	16
13	=	0,		41
14	=	21,	46
15	=	87,	70
16	=	148,	45
17	=	186,	45
18	=	243,	47
19	=	280,	47
20	=	0,		82
21	=	23,	91
22	=	59,	86
23	=	133,	92
24	=	172,	90
25	=	195,	70
26	=	216,	98
27	=	249,	77 

[INFO]
TOTAL REGIONS	= 	27
