# Tornie Mod Game Options (default values)
[Game Options]
Game Speed = 16
Concrete Required = false
Structures Degrade On Concrete = false
Fog of War = true
Start with Explored Map = false
Instant Build = true
Only One Palace = false
Rocket-Turrets Need Power = true
Sandworms Respawn = true
Killed Sandworms Drop Spice = true
Manual Carryall Drops = false
Maximum Number of Units Override = 999
Maximum Number of Harvesters Override = 10
Immortal Human Player = false
City Effects = false
