#!/usr/bin/env python3
"""Build data/Tornie.PAK from loose PNG files in data/.

PAK format (Dune Legacy / Westwood):
  Header:  [uint32_le offset, null-terminated name] × N, then uint32_le 0
  Body:    raw file data concatenated in entry order
Offsets are absolute byte positions in the file.
"""

import struct, os, sys
from pathlib import Path

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = Path(REPO) / "data"
MODS_TORNIE = Path(REPO) / "mods" / "Tornie"
OUT  = DATA / "Tornie.PAK"

# Some assets live in mods/Tornie/campaign/ rather than data/
# (the Rebels campaign scenarios ship with the mod on disk; data/
# holds engine-visible artifacts only). Resolve per entry below.
def resolve_entry(name):
    """Return (pak_entry_name, on_disk_path) for a given ENTRIES list entry.
    The on-disk path may live in either data/ (default) or in a subdir
    of mods/Tornie/ (e.g. mod-side Rebels scenarios). The pak_entry_name
    is what gets written into the PAK header — engine code calls pFileManager
    with bare filenames like 'scenr001.ini', so we must strip the
    'campaign/' source-path prefix and emit just the basename."""
    parts = name.split("/", 1)
    if parts[0] == "campaign":
        rel = parts[1] if len(parts) > 1 else ""
        base = MODS_TORNIE / "campaign"
        pak_name = rel                 # strip 'campaign/' prefix
    else:
        rel = name
        base = DATA
        pak_name = name
    direct = base / rel
    if direct.is_file():
        return pak_name, direct
    # case-insensitive fallback (Linux ext4 is case-sensitive; macOS/Windows are not)
    if base.is_dir():
        for candidate in base.iterdir():
            if candidate.name.lower() == rel.lower() and candidate.is_file():
                return pak_name, candidate
    return pak_name, None

ENTRIES = [
    # DuneCity 1.0.286: removed FlameTank.png, FlameTankIcon.png and
    # Deviator.png. Per user spec, vanilla tiles are reused (the
    # code in GFXManager.cpp falls back to ObjPic_Launcher_Gun for
    # FlameTank; vanilla ObjPic_Deviator_Gun for Deviator).  The
    # Tornie mod no longer carries custom tile art for these two
    # units.
    "HeraldNeu.png",
    "HeraldNeuMask.png",
    "HeraldRebels.png",
    "HeraldRebelsMask.png",
    "NeutralLauncherIcon.png",
    "PalaceTrikeAndQuadIcon.png",
    # DuneCity 1.0.254: Rocket Trike 91x55 sidebar icon for the player
    # sidebar. The user-supplied 8-bit palette PNG goes to data/ and
    # also mods/Tornie/data/ so it loads cross-mod (the loader at
    # GFXManager.cpp:2124 uses pFileManager->exists()). Without
    # these in the PAK the installed game falls back to the vanilla
    # TRIKE.WSA portrait for the Rocket Trike sidebar slot, which
    # looks wrong (the icon is supposed to distinguish rocket-trike
    # from regular trike at a glance). Mask companion is optional.
    "RocketTrikeIcon.png",
    "RocketTrikeIconMask.png",
    "REGIONN.INI",
    # DuneCity 1.0.252: Custom_IBM.pal ships inside Tornie.Pak so the
    # rebels-grey palette is available to any mod that loads the PAK
    # (the loader at GFXManager.cpp checks pFileManager->exists, which
    # finds the PAK-stored file via Pakfile::exists). The
    # "Custom_IBM.pal" loader overwrites palette entries 192-199 with
    # the rebels-grey values from the file.
    "Custom_IBM.pal",
    "Tornie_AdvancedWindtrap_gfx.png",
    "Tornie_AdvancedWindtrap_editor.png",
    "Tornie_AdvancedWindtrap_icon.png",
    "Tornie_SpiceRed.png",
    "Tornie_SpiceGreen.png",
    "PaulAtreidesMentat.png",
    "PaulAtreidesEyes.png",
    "PaulAtreidesMouth.png",
    "scenn001.ini",
    "scenn002.ini",
    "scenn003.ini",
    "scenn004.ini",
    "scenn005.ini",
    "scenn006.ini",
    "scenn007.ini",
    "scenn008.ini",
    "scenn009.ini",
    "scenn010.ini",
    "scenn011.ini",
    "scenn012.ini",
    "scenn013.ini",
    "scenn014.ini",
    "scenn015.ini",
    "scenn016.ini",
    "scenn017.ini",
    "scenn018.ini",
    "scenn019.ini",
    "scenn020.ini",
    "scenn021.ini",
    "scenn022.ini",
# DuneCity/Tornie: 8th campaign section (Rebels) — scenr001-022.ini
    # (generated by scripts/make-rebels-scenarios.py, ships under
    # mods/Tornie/campaign/; resolve_entry handles the cross-folder lookup)
    "campaign/scenr001.ini",
    "campaign/scenr002.ini",
    "campaign/scenr003.ini",
    "campaign/scenr004.ini",
    "campaign/scenr005.ini",
    "campaign/scenr006.ini",
    "campaign/scenr007.ini",
    "campaign/scenr008.ini",
    "campaign/scenr009.ini",
    "campaign/scenr010.ini",
    "campaign/scenr011.ini",
    "campaign/scenr012.ini",
    "campaign/scenr013.ini",
    "campaign/scenr014.ini",
    "campaign/scenr015.ini",
    "campaign/scenr016.ini",
    "campaign/scenr017.ini",
    "campaign/scenr018.ini",
    "campaign/scenr019.ini",
    "campaign/scenr020.ini",
    "campaign/scenr021.ini",
    "campaign/scenr022.ini",
    # DuneCity/Tornie: REGIONR.INI for Rebels career.  Sourced from
    # mods/Tornie/campaign/; resolve_entry() handles cross-folder +
    # case-insensitive lookup, and emits the PAK entry under the bare
    # basename REGIONR.INI.
    "campaign/REGIONR.INI",
]

def main():
    blobs = []
    paken_names = []
    for name in ENTRIES:
        pak_name, path = resolve_entry(name)
        if path is None:
            print(f"ERROR: missing {name} (looked in data/ and mods/Tornie/campaign/)", file=sys.stderr)
            sys.exit(1)
        blobs.append(open(path, "rb").read())
        paken_names.append(pak_name)

    # header size: per entry 4 bytes offset + len(name)+1 null, plus 4 byte terminator
    header_size = sum(4 + len(n) + 1 for n in paken_names) + 4

    # compute absolute offsets
    data_offset = 0
    offsets = []
    for blob in blobs:
        offsets.append(header_size + data_offset)
        data_offset += len(blob)

    with open(OUT, "wb") as f:
        # PAK entry names are paken_names (bare filenames like 'scenr001.ini',
        # even when the source file lives in mods/Tornie/campaign/). Engine
        # code calls pFileManager with bare filenames, so writing
        # 'campaign/scenr001.ini' to the PAK header would defeat lookup.
        for name, off in zip(paken_names, offsets):
            f.write(struct.pack("<I", off))
            f.write(name.encode("ascii") + b"\x00")
        f.write(struct.pack("<I", 0))  # terminator
        for blob in blobs:
            f.write(blob)

    print(f"Wrote {os.path.getsize(OUT)} bytes to {OUT}")
    print(f"  {len(ENTRIES)} entries packed")

if __name__ == "__main__":
    main()
